In [124]:
import pandas as pd
import numpy as np
import re

In [125]:
'''
L.S. You made good use of pandas. The code seems to work and looks solid. 

The presentation was very clear!

Also, I really liked that you analysed the data with 4 questions in mind. This helps you
to structure everything nicely. 
'''

columns = ['incident_id', 'start_time', 'incident_type', 'l_1', 'l_2', 'l_3', 'date', 'year', 'month', 'month_name', 'day_nr', 'day_name', 'week_nr', 'quartile', 'priority', 'hour', 'part_day', 'place_type', 'place_function', 'neighbourhood', 'district', 'town', 'municipality']

fire = pd.read_csv('main.csv')

fire.head()

,index,classification_1,classification_2,classification_3,year,month_nr,month_name,day_nr,day_name,week_nr,priority,hour,day_part,objecttype,object_funtion,neighbourhood,city_part,city
0,0,Dienstverlening,Burger Dienst,Stankoverlast Burger,2009,12,December ...,7,Dinsdag ...,50,2,20,Avond ...,bag ...,Woonfunctie ...,Kinkerbuurt ...,Stadsdeel West ...,Amsterdam ...
1,1,Brand,Wegvervoer,,2012,10,Oktober ...,13,Zondag ...,41,1,22,Avond ...,weg ...,Straat ...,Buikslotermeer ...,Stadsdeel Noord ...,Amsterdam ...
2,3,Dienstverlening,Dieren,Te water,2012,4,April ...,15,Maandag ...,15,3,20,Avond ...,water ...,Kanalen en rivieren ...,Buitenveldert-Oost ...,Stadsdeel Zuid ...,Amsterdam ...
3,4,Brand,Wegvervoer,,2012,8,Augustus ...,17,Zaterdag ...,33,1,3,Nacht ...,weg ...,Straat ...,Hoofddorppleinbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
4,6,Dienstverlening,Burger Dienst,Liftopsluiting Burger,2006,2,Februari ...,18,Zondag ...,7,3,0,Nacht ...,bag ...,Woonfunctie ...,Nieuwendam-Noord ...,Stadsdeel Noord ...,Amsterdam ...

In [126]:
#del fire['incident_id']
#del fire['start_tijd']
#del fire['datum']
#del fire['woonplaats']

In [127]:
#deleting unnecessary columns

In [128]:
fire.head(15)

,index,classification_1,classification_2,classification_3,year,month_nr,month_name,day_nr,day_name,week_nr,priority,hour,day_part,objecttype,object_funtion,neighbourhood,city_part,city
0,0,Dienstverlening,Burger Dienst,Stankoverlast Burger,2009,12,December ...,7,Dinsdag ...,50,2,20,Avond ...,bag ...,Woonfunctie ...,Kinkerbuurt ...,Stadsdeel West ...,Amsterdam ...
1,1,Brand,Wegvervoer,,2012,10,Oktober ...,13,Zondag ...,41,1,22,Avond ...,weg ...,Straat ...,Buikslotermeer ...,Stadsdeel Noord ...,Amsterdam ...
2,3,Dienstverlening,Dieren,Te water,2012,4,April ...,15,Maandag ...,15,3,20,Avond ...,water ...,Kanalen en rivieren ...,Buitenveldert-Oost ...,Stadsdeel Zuid ...,Amsterdam ...
3,4,Brand,Wegvervoer,,2012,8,Augustus ...,17,Zaterdag ...,33,1,3,Nacht ...,weg ...,Straat ...,Hoofddorppleinbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
4,6,Dienstverlening,Burger Dienst,Liftopsluiting Burger,2006,2,Februari ...,18,Zondag ...,7,3,0,Nacht ...,bag ...,Woonfunctie ...,Nieuwendam-Noord ...,Stadsdeel Noord ...,Amsterdam ...
5,7,Dienstverlening,Burger Dienst,Wateroverlast Burger,2007,9,September ...,10,Dinsdag ...,37,2,20,Avond ...,bag ...,Woonfunctie ...,Nieuwendam-Noord ...,Stadsdeel Noord ...,Amsterdam ...
6,8,Dienstverlening,MKA,,2012,10,Oktober ...,11,Vrijdag ...,41,1,10,Ochtend ...,bag ...,Woonfunctie ...,IJburg West ...,Stadsdeel Oost ...,Amsterdam ...
7,10,Gezondheid,CPA gezondheid,AED Reanimatie CPA,2010,7,Juli ...,17,Zondag ...,28,1,18,Avond ...,bag ...,Woonfunctie ...,Slotervaart ...,Stadsdeel Nieuw-West ...,Amsterdam ...
8,11,Gezondheid,Onwel/ziekte,,2015,5,Mei ...,4,Dinsdag ...,19,1,21,Avond ...,bag ...,Woonfunctie ...,Rijnbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
9,12,Brand,kleine inzet Brand,Brandgerucht kl.inzet,2011,4,April ...,11,Dinsdag ...,15,1,22,Avond ...,bag ...,Woonfunctie ...,IJburg Zuid ...,Stadsdeel Oost ...,Amsterdam ...
10,13,Dienstverlening,Algemeen dienst,Stormschade Algem,2008,11,November ...,21,Zaterdag ...,47,3,10,Ochtend ...,bag ...,Woonfunctie ...,Waterland ...,Stadsdeel Noord ...,Amsterdam ...
11,15,Brand,Buitenbrand brand,Container buitbr,2010,12,December ...,31,Zaterdag ...,52,1,19,Avond ...,weg ...,Straat ...,Slotervaart ...,Stadsdeel Nieuw-West ...,Amsterdam ...
12,16,Brand,Buitenbrand brand,Overig buitbr,2005,12,December ...,26,Dinsdag ...,52,2,1,Nacht ...,weg ...,Straat ...,Westindische buurt ...,Stadsdeel West ...,Amsterdam ...
13,17,Brand,kleine inzet Brand,Brandgerucht kl.inzet,2012,2,Februari ...,6,Dinsdag ...,6,1,13,Middag ...,bag ...,Kantoorfunctie ...,Amstel III/Bullewijk ...,Stadsdeel Zuidoost ...,Amsterdam ...
14,21,Brand,Binnenbrand brand,Ontmoeting binbr,2011,6,Juni ...,18,Zondag ...,24,1,15,Middag ...,bag ...,Bijeenkomstfunctie ...,Burgwallen-Nieuwe Zijde ...,Stadsdeel Centrum ...,Amsterdam ...

In [129]:
indexCity = fire[ fire['city'] == 'Amsterdam'].index

indexCity

Int64Index([], dtype='int64')

In [64]:
#fire.drop(indexCity, inplace = True)

In [77]:
#fire.head(15)

In [130]:
'''
L.S. Looks good! 
'''

import pymysql
from sqlalchemy import create_engine

In [131]:
engine = create_engine('mysql+pymysql://root:@localhost/Amsterdam')

In [30]:
fire.to_sql('fire_data', engine, if_exists='replace', index=True)

In [22]:
fire.dtypes

index                int64
classification_1    object
classification_2    object
classification_3    object
year                 int64
month_nr             int64
month_name          object
day_nr               int64
day_name            object
week_nr              int64
quartile             int64
priority             int64
hour                 int64
day_part            object
objecttype          object
object_funtion      object
neighbourhood       object
city_part           object
city                object
dtype: object

In [20]:
fire.rename(columns = {'maand_nr': 'month_nr', 'maand_naam': 'month_name', 'dag_nr': 'day_nr', 'dag_naam':'day_name', 'kwartaal':'quartile', 'prioriteit':'priority', 'uur':'hour', 'dagdeel':'day_part', 'objectfunctie':'object_funtion', 'buurt':'neighbourhood', 'wijk':'city_part', 'gemeente':'city'}, inplace = True)

In [21]:
fire.head()

,index,classification_1,classification_2,classification_3,year,month_nr,month_name,day_nr,day_name,week_nr,quartile,priority,hour,day_part,objecttype,object_funtion,neighbourhood,city_part,city
0,0,Dienstverlening,Burger Dienst,Stankoverlast Burger,2009,12,December ...,7,Dinsdag ...,50,4,2,20,Avond ...,bag ...,Woonfunctie ...,Kinkerbuurt ...,Stadsdeel West ...,Amsterdam ...
1,1,Brand,Wegvervoer,,2012,10,Oktober ...,13,Zondag ...,41,4,1,22,Avond ...,weg ...,Straat ...,Buikslotermeer ...,Stadsdeel Noord ...,Amsterdam ...
2,2,Brand,kleine inzet Brand,Nacontrole kl.inzet,2006,2,Februari ...,18,Zondag ...,7,1,1,15,Middag ...,...,...,...,...,Haarlemmermeer ...
3,3,Dienstverlening,Dieren,Te water,2012,4,April ...,15,Maandag ...,15,2,3,20,Avond ...,water ...,Kanalen en rivieren ...,Buitenveldert-Oost ...,Stadsdeel Zuid ...,Amsterdam ...
4,4,Brand,Wegvervoer,,2012,8,Augustus ...,17,Zaterdag ...,33,3,1,3,Nacht ...,weg ...,Straat ...,Hoofddorppleinbuurt ...,Stadsdeel Zuid ...,Amsterdam ...

In [23]:
del fire['quartile']

In [24]:
del fire['index']

In [27]:
fire.head()

,classification_1,classification_2,classification_3,year,month_nr,month_name,day_nr,day_name,week_nr,priority,hour,day_part,objecttype,object_funtion,neighbourhood,city_part,city
0,Dienstverlening,Burger Dienst,Stankoverlast Burger,2009,12,December ...,7,Dinsdag ...,50,2,20,Avond ...,bag ...,Woonfunctie ...,Kinkerbuurt ...,Stadsdeel West ...,Amsterdam ...
1,Brand,Wegvervoer,,2012,10,Oktober ...,13,Zondag ...,41,1,22,Avond ...,weg ...,Straat ...,Buikslotermeer ...,Stadsdeel Noord ...,Amsterdam ...
2,Brand,kleine inzet Brand,Nacontrole kl.inzet,2006,2,Februari ...,18,Zondag ...,7,1,15,Middag ...,...,...,...,...,Haarlemmermeer ...
3,Dienstverlening,Dieren,Te water,2012,4,April ...,15,Maandag ...,15,3,20,Avond ...,water ...,Kanalen en rivieren ...,Buitenveldert-Oost ...,Stadsdeel Zuid ...,Amsterdam ...
4,Brand,Wegvervoer,,2012,8,Augustus ...,17,Zaterdag ...,33,1,3,Nacht ...,weg ...,Straat ...,Hoofddorppleinbuurt ...,Stadsdeel Zuid ...,Amsterdam ...

In [197]:
import os

In [198]:
file_list = [f for f in os.listdir('./cat') if f.endswith('.csv')]
data_sets = [pd.read_csv(os.path.join('./cat', f)) for f in file_list]

cat_data = pd.concat(data_sets, axis = 1)

In [199]:
os.getcwd()

'/Users/louise/Documents/ironhack/project week 2 '

In [200]:
newyear = pd.concat(data_sets, axis = 1, join='inner')

In [202]:


#del cat_data2['classification_1']


#cat_data2.insert(1, 'classification_1', ['Brand', 'Dienstverlening', 'Gezondheid', 'Verkeer'])

#cat_data2['classification_1'] = ['Brand', 'Dienstverlening', 'Gezondheid', 'Verkeer']

newyear2 = newyear.append(westpoort3, ignore_index = True)



#city.rename(columns = {'year': 'Year'})

ValueError: Plan shapes are not aligned

In [115]:
water.to_sql('question_4', engine, if_exists='replace', index=True)

In [43]:
#fire['classification_1'] = fire['classification_1'].str.replace('Alarm', 'Brand')

In [45]:
fire

,classification_1,classification_2,classification_3,year,month_nr,month_name,day_nr,day_name,week_nr,priority,hour,day_part,objecttype,object_funtion,neighbourhood,city_part,city
0,Dienstverlening,Burger Dienst,Stankoverlast Burger,2009,12,December ...,7,Dinsdag ...,50,2,20,Avond ...,bag ...,Woonfunctie ...,Kinkerbuurt ...,Stadsdeel West ...,Amsterdam ...
1,Brand,Wegvervoer,,2012,10,Oktober ...,13,Zondag ...,41,1,22,Avond ...,weg ...,Straat ...,Buikslotermeer ...,Stadsdeel Noord ...,Amsterdam ...
2,Brand,kleine inzet Brand,Nacontrole kl.inzet,2006,2,Februari ...,18,Zondag ...,7,1,15,Middag ...,...,...,...,...,Haarlemmermeer ...
3,Dienstverlening,Dieren,Te water,2012,4,April ...,15,Maandag ...,15,3,20,Avond ...,water ...,Kanalen en rivieren ...,Buitenveldert-Oost ...,Stadsdeel Zuid ...,Amsterdam ...
4,Brand,Wegvervoer,,2012,8,Augustus ...,17,Zaterdag ...,33,1,3,Nacht ...,weg ...,Straat ...,Hoofddorppleinbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
5,Brand,Buitenbrand brand,Afval/ruigte buitbr,2006,12,December ...,21,Vrijdag ...,51,2,20,Avond ...,...,...,...,...,Haarlemmermeer ...
6,Dienstverlening,Burger Dienst,Liftopsluiting Burger,2006,2,Februari ...,18,Zondag ...,7,3,0,Nacht ...,bag ...,Woonfunctie ...,Nieuwendam-Noord ...,Stadsdeel Noord ...,Amsterdam ...
7,Dienstverlening,Burger Dienst,Wateroverlast Burger,2007,9,September ...,10,Dinsdag ...,37,2,20,Avond ...,bag ...,Woonfunctie ...,Nieuwendam-Noord ...,Stadsdeel Noord ...,Amsterdam ...
8,Dienstverlening,MKA,,2012,10,Oktober ...,11,Vrijdag ...,41,1,10,Ochtend ...,bag ...,Woonfunctie ...,IJburg West ...,Stadsdeel Oost ...,Amsterdam ...
9,Brand,Buitenbrand brand,Overig buitbr,2008,1,Januari ...,3,Vrijdag ...,1,1,23,Avond ...,weg ...,Straat ...,Thamerdal ...,Wijk 25 Thamerdal ...,Uithoorn ...
10,Gezondheid,CPA gezondheid,AED Reanimatie CPA,2010,7,Juli ...,17,Zondag ...,28,1,18,Avond ...,bag ...,Woonfunctie ...,Slotervaart ...,Stadsdeel Nieuw-West ...,Amsterdam ...
11,Gezondheid,Onwel/ziekte,,2015,5,Mei ...,4,Dinsdag ...,19,1,21,Avond ...,bag ...,Woonfunctie ...,Rijnbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
12,Brand,kleine inzet Brand,Brandgerucht kl.inzet,2011,4,April ...,11,Dinsdag ...,15,1,22,Avond ...,bag ...,Woonfunctie ...,IJburg Zuid ...,Stadsdeel Oost ...,Amsterdam ...
13,Dienstverlening,Algemeen dienst,Stormschade Algem,2008,11,November ...,21,Zaterdag ...,47,3,10,Ochtend ...,bag ...,Woonfunctie ...,Waterland ...,Stadsdeel Noord ...,Amsterdam ...
14,Dienstverlening,Algemeen dienst,Dieren Algem,2005,12,December ...,29,Vrijdag ...,52,2,10,Ochtend ...,...,...,...,...,Haarlemmermeer ...
15,Brand,Buitenbrand brand,Container buitbr,2010,12,December ...,31,Zaterdag ...,52,1,19,Avond ...,weg ...,Straat ...,Slotervaart ...,Stadsdeel Nieuw-West ...,Amsterdam ...
16,Brand,Buitenbrand brand,Overig buitbr,2005,12,December ...,26,Dinsdag ...,52,2,1,Nacht ...,weg ...,Straat ...,Westindische buurt ...,Stadsdeel West ...,Amsterdam ...
17,Brand,kleine inzet Brand,Brandgerucht kl.inzet,2012,2,Februari ...,6,Dinsdag ...,6,1,13,Middag ...,bag ...,Kantoorfunctie ...,Amstel III/Bullewijk ...,Stadsdeel Zuidoost ...,Amsterdam ...
18,Ongeval,Spoorvervoer,Aanrijding letsel,2012,4,April ...,3,Woensdag ...,14,1,18,Avond ...,...,...,...,...,Ouder-Amstel ...
19,Brand,Aut.Alarm brand,.OMS melding brand,2009,8,Augustus ...,11,Woensdag ...,33,1,20,Avond ...,bag ...,Gezondheidszorgfunctie ...,Bankras ...,Wijk 00 Amstelveen ...,Amstelveen ...
20,Brand,Aut.Alarm brand,.PAC melding brand,2010,11,November ...,14,Maandag ...,45,1,15,Middag ...,bag ...,Industriefunctie ...,Bovenkerk en Legmeer ...,Wijk 00 Amstelveen ...,Amstelveen ...
21,Brand,Binnenbrand brand,Ontmoeting binbr,2011,6,Juni ...,18,Zondag ...,24,1,15,Middag ...,bag ...,Bijeenkomstfunctie ...,Burgwallen-Nieuwe Zijde ...,Stadsdeel Centrum ...,Amsterdam ...
22,Dienstverlening,Brandweer,Meting,2012,12,December ...,14,Zaterdag ...,50,1,19,Avond ...,bag ...,Woonfunctie ...,Zijdelwaard ...,Wijk 35 Zijdelwaard ...,Uithoorn ...
23,Brand,Aut.Alarm brand,.OMS melding brand,2010,6,Juni ...,15,Woensdag ...,24,1,18,Avond ...,bag ...,Kantoorfunctie ...,Buiksloterham ...,Stadsdeel Noord ...,Amsterdam ...
24,Dienstverlening,Onderzoek dienstverl,Metingen onderz,2007,5,Mei ...,9,Donderdag ...,19,1,23,Avond ...,bag ...,Woonfunctie ...,Indische Buurt West ...,Stadsdeel Oost ...,Amsterdam ...
25,Ongeval,Water,Persoon te water,2015,5,Mei ...,10,Maandag ...,19,1,16,Middag ...,water ...,Grachtengordel ...,Weesperbuurt/Plantage ...,Stadsdeel Centrum ...,Amsterdam ...
26,Brand,Autom. brand,Br Criterium OMS,2015,1,Januari ...,3,Zondag ...,1,1,0,Nacht ...,bag ...,Celfunctie ...,Spaarndammer- en Zeeheldenbuurt ...,Stadsdeel West ...,Amsterdam ...
27,Brand,Buitenbrand brand,Container buitbr,2009,1,Januari ...,1,Vrijdag ...,1,2,7,Ochtend ...,weg ...,Straat ...,Holendrecht/Reigersbos ...,Stadsdeel Zuidoost ...,Amsterdam ...
28,Brand,Autom. brand,Brandmelding PAC,2014,6,Juni ...,27,Zaterdag ...,26,1,2,Nacht ...,bag ...,Winkelfunctie ...,Grachtengordel-West ...,Stadsdeel Centrum ...,Amsterdam ...
29,Gezondheid,CPA gezondheid,Afh/Oph pat zonder spoed CPA,2009,10,Oktober ...,1,Vrijdag ...,40,2,12,Middag ...,bag ...,Woonfunctie ...,Scheldebuurt ...,Stadsdeel Zuid ...,Amsterdam ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127835,Brand,Buiten,Container,2013,12,December ...,31,Woensdag ...,1,2,12,Middag ...,weg ...,Straat ...,Slotermeer-Noordoost ...,Stadsdeel Nieuw-West ...,Amsterdam ...
127836,Gezondheid,B-rit zorg,,2015,1,Januari ...,27,Woensdag ...,5,2,16,Middag ...,bag ...,Woonfunctie ...,Holendrecht/Reigersbos ...,Stadsdeel Zuidoost ...,Amsterdam ...
127837,Gezondheid,CPA gezondheid,Afh.pat zonder spoed CPA,2006,1,Januari ...,29,Maandag ...,4,2,9,Ochtend ...,bag ...,Woonfunctie ...,Apollobuurt ...,Stadsdeel Zuid ...,Amsterdam ...
127838,Brand,Binnenbrand brand,.Wonen binbr,2008,8,Augustus ...,6,Donderdag ...,32,1,10,Ochtend ...,bag ...,Woonfunctie ...,Duivelseiland ...,Stadsdeel Zuid ...,Amsterdam ...
127839,Brand,kleine inzet Brand,Brandgerucht kl.inzet,2010,5,Mei ...,29,Zondag ...,21,1,15,Middag ...,bag ...,Woonfunctie ...,Transvaalbuurt ...,Stadsdeel Oost ...,Amsterdam ...
127840,Overige,AAS overig,Inzet SPL AAS,2006,8,Augustus ...,25,Zaterdag ...,34,3,5,Nacht ...,...,...,...,...,Soest ...
127841,Leefmilieu,Stank,,2014,3,Maart ...,16,Maandag ...,11,3,5,Nacht ...,bag ...,Woonfunctie ...,Oude Pijp ...,Stadsdeel Zuid ...,Amsterdam ...
127842,Dienstverlening,Algemeen dienst,Stormschade Algem,2007,1,Januari ...,18,Vrijdag ...,3,2,10,Ochtend ...,bag ...,Overige gebruiksfunctie ...,Keizer Karelpark-Oost ...,Wijk 00 Amstelveen ...,Amstelveen ...
127843,Dienstverlening,Burger Dienst,Stankoverlast Burger,2010,8,Augustus ...,25,Donderdag ...,34,1,19,Avond ...,bag ...,Woonfunctie ...,Transvaalbuurt ...,Stadsdeel Oost ...,Amsterdam ...
127844,Dienstverlening,Brandweer,Aan derden,2014,3,Maart ...,15,Zondag ...,11,1,17,Middag ...,bag ...,Woonfunctie ...,Rijnbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
127845,Gezondheid,Reanimatie,,2012,12,December ...,31,Dinsdag ...,1,1,17,Middag ...,bag ...,Woonfunctie ...,"Bijlmer-Centrum (D, F, H) ...",Stadsdeel Zuidoost ...,Amsterdam ...
127846,Brand,Buitenbrand brand,Container buitbr,2007,4,April ...,14,Zondag ...,15,2,4,Nacht ...,weg ...,Straat ...,Jordaan ...,Stadsdeel Centrum ...,Amsterdam ...
127847,Brand,Aut.Alarm brand,.OMS melding brand,2007,6,Juni ...,4,Dinsdag ...,23,1,13,Middag ...,bag ...,Gezondheidszorgfunctie ...,Bankras ...,Wijk 00 Amstelveen ...,Amstelveen ...
127848,Brand,Aut.Alarm brand,.PAC melding brand,2010,4,April ...,19,Dinsdag ...,16,1,8,Ochtend ...,bag ...,Kantoorfunctie ...,Verrijn Stuart ...,Wijk 00 Diemen-Zuid ...,Diemen ...
127849,Dienstverlening,Brandweer,Aan derden,2013,7,Juli ...,4,Vrijdag ...,27,1,8,Ochtend ...,bag ...,Kantoorfunctie ...,Lutkemeer en Ookmeer ...,Stadsdeel Nieuw-West ...,Amsterdam ...
127850,Brand,kleine inzet Brand,Brandgerucht kl.inzet,2007,1,Januari ...,30,Woensdag ...,5,1,18,Avond ...,bag ...,Overige gebruiksfunctie ...,De Weteringschans ...,Stadsdeel Centrum ...,Amsterdam ...
127851,Brand,Aut.Alarm brand,.OMS melding brand,2007,10,Oktober ...,30,Woensdag ...,44,1,1,Nacht ...,bag ...,Celfunctie ...,Schinkelbuurt ...,Stadsdeel Zuid ...,Amsterdam ...
127852,Dienstverlening,Burger Dienst,Liftopsluiting Burger,2006,6,Juni ...,21,Donderdag ...,25,3,17,Middag ...,bag ...,Woonfunctie ...,"Bijlmer-Oost (E, G, K) ...",Stadsdeel Zuidoost ...,Amsterdam ...
127853,Brand,Aut.Alarm brand,.OMS melding brand,2010,5,Mei ...,7,Zaterdag ...,18,1,8,Ochtend ...,bag ...,Kantoorfunctie ...,Amstel III/Bullewijk ...,Stadsdeel Zuidoost ...,Amsterdam ...
127854,Brand,Autom. brand,,2012,3,Maart ...,29,Vrijdag ...,13,1,0,Nacht ...,bag ...,Kantoorfunctie ...,Buitengebied-Zuid ...,Wijk 00 Amstelveen ...,Amstelveen ...
127855,Dienstverlening,Algemeen dienst,Stormschade Algem,2007,1,Januari ...,18,Vrijdag ...,3,3,16,Middag ...,bag ...,Overige gebruiksfunctie ...,Banne Buiksloot ...,Stadsdeel Noord ...,Amsterdam ...
127856,Brand,Buiten,Container,2014,3,Maart ...,15,Zondag ...,11,2,7,Ochtend ...,weg ...,Straat ...,Tuindorp Nieuwendam ...,Stadsdeel Noord ...,Amsterdam ...
127857,Brand,Autom. brand,Br Criterium OMS,2015,5,Mei ...,4,Dinsdag ...,19,1,21,Avond ...,bag ...,Logiesfunctie ...,Buiksloterham ...,Stadsdeel Noord ...,Amsterdam ...
127858,Brand,Buitenbrand brand,Container buitbr,2006,12,December ...,26,Woensdag ...,52,1,20,Avond ...,weg ...,Straat ...,Oostzanerwerf ...,Stadsdeel Noord ...,Amsterdam ...
127859,Brand,Buitenbrand brand,Afval/ruigte buitbr,2008,1,Januari ...,4,Zaterdag ...,1,1,4,Nacht ...,weg ...,Regionale weg ...,Middenmeer ...,Stadsdeel Oost ...,Amsterdam ...
127860,Dienstverlening,Brandweer,Meting,2012,5,Mei ...,2,Donderdag ...,18,1,15,Middag ...,bag ...,Bijeenkomstfunctie ...,De Weteringschans ...,Stadsdeel Centrum ...,Amsterdam ...
127861,Brand,Voertuig brand,Auto brand,2009,1,Januari ...,21,Donderdag ...,4,1,0,Nacht ...,weg ...,Straat ...,Slotermeer-Noordoost ...,Stadsdeel Nieuw-West ...,Amsterdam ...
127862,Brand,Autom. brand,,2012,9,September ...,4,Woensdag ...,36,1,7,Ochtend ...,bag ...,Woonfunctie ...,Keizer Karelpark-West ...,Wijk 00 Amstelveen ...,Amstelveen ...
127863,Brand,Aut.Alarm brand,.OMS melding brand,2010,1,Januari ...,15,Zaterdag ...,2,1,16,Middag ...,bag ...,Woonfunctie ...,Vondelbuurt ...,Stadsdeel West ...,Amsterdam ...
127864,Dienstverlening,Brandweer,Bijstand,2012,8,Augustus ...,17,Zaterdag ...,33,1,17,Middag ...,...,...,...,...,De Ronde Venen ...

In [48]:

# Get names of indexes for which column Age has value 30
indexNames = fire[ fire['classification_1'] == 'Overige' ].index
 
# Delete these row indexes from dataFrame
fire2 = fire.drop(indexNames , inplace=True)

fire2

In [220]:
water_zuid = pd.read_csv('./cat/water_zuid.csv')

FileNotFoundError: [Errno 2] File b'./cat/water_zuid.csv' does not exist: b'./cat/water_zuid.csv'

In [192]:
westpoort

   Year2  Westpoort
0   2008          1
1   2009          2
2   2011          1
3   2012          2

In [193]:
westpoort2 = pd.DataFrame([[2006, 0], [2007, 0], [2010, 0], [2013, 0], [2014, 0], [2015, 0]], columns = ['Year2', 'Westpoort'])

In [194]:
westpoort2

   Year2  Westpoort
0   2006          0
1   2007          0
2   2010          0
3   2013          0
4   2014          0
5   2015          0

In [195]:
westpoort3 = westpoort.append(westpoort2, ignore_index = True)

In [196]:
westpoort3

   Year2  Westpoort
0   2008          1
1   2009          2
2   2011          1
3   2012          2
4   2006          0
5   2007          0
6   2010          0
7   2013          0
8   2014          0
9   2015          0

In [273]:
file_list = [f for f in os.listdir('./cat') if f.endswith('.csv')]
data_sets = [pd.read_csv(os.path.join('./cat', f)) for f in file_list]

water = pd.concat(data_sets, axis = 1)

In [271]:


water_tot = pd.read_csv('./cat/water.csv')

In [274]:
water

,Month2,Noord,month_nr,index,Month2,Zuid,month_nr,Month2,Oost,month_nr,...,month_nr,Month2,West,month_nr,Month2,Westpoort,month_nr,Month,Zuidoost,month_nr
0,Januari ...,26,1,0,Januari ...,16,1,Januari ...,26,1,...,1,Januari ...,16,1,Januari ...,4,1,Januari ...,11,1
1,Februari ...,14,2,1,Februari ...,13,2,Februari ...,21,2,...,2,Februari ...,12,2,Februari ...,7,2,Februari ...,3,2
2,Maart ...,15,3,11,Maart,0,3,Maart ...,15,3,...,3,Maart ...,9,3,Maart ...,6,3,Maart ...,5,3
3,April ...,21,4,2,April ...,9,4,April ...,18,4,...,4,April ...,12,4,April ...,5,4,April ...,3,4
4,Mei ...,33,5,3,Mei ...,10,5,Mei ...,18,5,...,5,Mei ...,17,5,Mei ...,6,5,Mei ...,16,5
5,Juni ...,41,6,4,Juni ...,14,6,Juni ...,16,6,...,6,Juni ...,14,6,Juni ...,4,6,Juni ...,12,6
6,Juli ...,66,7,5,Juli ...,10,7,Juli ...,20,7,...,7,Juli ...,13,7,Juli ...,3,7,Juli ...,14,7
7,Augustus ...,61,8,6,Augustus ...,19,8,Augustus ...,18,8,...,8,Augustus ...,11,8,Augustus ...,3,8,Augustus ...,20,8
8,September ...,52,9,7,September ...,7,9,September ...,17,9,...,9,September ...,11,9,September ...,4,9,September ...,10,9
9,Oktober ...,29,10,8,Oktober ...,7,10,Oktober ...,20,10,...,10,Oktober ...,20,10,Oktober ...,6,10,Oktober ...,5,10
10,November ...,20,11,9,November ...,7,11,November ...,17,11,...,11,November ...,8,11,November ...,4,11,November ...,5,11
11,December ...,25,12,10,December ...,16,12,December ...,12,12,...,12,December ...,18,12,December ...,5,12,December ...,13,12

In [275]:
del water['index']
del water['Month2']
del water['month_nr']

In [276]:
water

,Noord,Zuid,Oost,Total,NieuwWest,Centrum,West,Westpoort,Month,Zuidoost
0,26,16,26,172,14,57,16,4,Januari ...,11
1,14,13,21,123,10,41,12,7,Februari ...,3
2,15,0,15,105,7,47,9,6,Maart ...,5
3,21,9,18,126,10,48,12,5,April ...,3
4,33,10,18,168,16,50,17,6,Mei ...,16
5,41,14,16,173,15,54,14,4,Juni ...,12
6,66,10,20,176,9,38,13,3,Juli ...,14
7,61,19,18,204,18,50,11,3,Augustus ...,20
8,52,7,17,170,15,53,11,4,September ...,10
9,29,7,20,141,16,36,20,6,Oktober ...,5
10,20,7,17,109,7,40,8,4,November ...,5
11,25,16,12,152,21,41,18,5,December ...,13

In [250]:
del water['index']

In [277]:
water

col_order = ['Month','Total', 'Centrum', 'NieuwWest', 'Noord', 'Oost', 'West', 'Westpoort', 'Zuid', 'Zuidoost']

water = water[col_order]
water

,Month,Total,Centrum,NieuwWest,Noord,Oost,West,Westpoort,Zuid,Zuidoost
0,Januari ...,172,57,14,26,26,16,4,16,11
1,Februari ...,123,41,10,14,21,12,7,13,3
2,Maart ...,105,47,7,15,15,9,6,0,5
3,April ...,126,48,10,21,18,12,5,9,3
4,Mei ...,168,50,16,33,18,17,6,10,16
5,Juni ...,173,54,15,41,16,14,4,14,12
6,Juli ...,176,38,9,66,20,13,3,10,14
7,Augustus ...,204,50,18,61,18,11,3,19,20
8,September ...,170,53,15,52,17,11,4,7,10
9,Oktober ...,141,36,16,29,20,20,6,7,5
10,November ...,109,40,7,20,17,8,4,7,5
11,December ...,152,41,21,25,12,18,5,16,13

In [278]:
water.to_sql('question_4', engine, if_exists='replace', index=True)

In [217]:
#newyear.rename(columns = {'year': 'Year'})

   Oost  Zuid  Noord  Year  Centrum  Westpoort  NieuwWest  Zuidoost  West
0    25    19     14  2006       11          0         31        19    39
1    24    18     14  2007       15          0         31         8    18
2    18     8     13  2008       11          1         23         9     9
3    24    22     27  2009       20          2         67        20    23
4    26    30     19  2010       20          0         42        14    28
5    22    12     10  2011       10          1         42        16    16
6    18    23      8  2012        8          2         28        10    11
7    15     8     10  2013        4          0         18         5     8
8    21    15      7  2014        3          0         27        12    17
9    29    18      9  2015        2          0         67        15    17

In [221]:
#data = pd.read_sql_query('SELECT * FROM Amsterdam.water_zuid', engine)

In [224]:
#zuid2 = pd.DataFrame([['Maart', 0, 3]], columns = ['Month2', 'Zuid', 'month_nr'])

In [225]:
#zuid2

  Month2  Zuid  month_nr
0  Maart     0         3

In [226]:
#zuid3 = data.append(zuid2, ignore_index = True)

In [227]:
#zuid3

                                               Month2  Zuid  month_nr
0   Januari                                       ...    16         1
1   Februari                                      ...    13         2
2   April                                         ...     9         4
3   Mei                                           ...    10         5
4   Juni                                          ...    14         6
5   Juli                                          ...    10         7
6   Augustus                                      ...    19         8
7   September                                     ...     7         9
8   Oktober                                       ...     7        10
9   November                                      ...     7        11
10  December                                      ...    16        12
11                                              Maart     0         3

In [228]:
#zuid3.to_sql('water_zuid', engine, if_exists='replace', index=True)

In [279]:
water.to_csv('question_4.csv')

In [262]:
water2 = pd.concat([water_tot, water], ignore_index = True)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

ValueError: Plan shapes are not aligned

In [260]:
water2

NameError: name 'water2' is not defined

In [264]:
water.shape

(12, 27)

In [265]:
water_tot.shape

(12, 3)

In [286]:
q3 = pd.read_csv('./cat/question_3.csv')

In [287]:
q3

,index,Oost,Zuid,Noord,year,Centrum,Westpoort,NieuwWest,Zuidoost,West
0,0,25,19,14,2006,11,0,31,19,39
1,1,24,18,14,2007,15,0,31,8,18
2,2,18,8,13,2008,11,1,23,9,9
3,3,24,22,27,2009,20,2,67,20,23
4,4,26,30,19,2010,20,0,42,14,28
5,5,22,12,10,2011,10,1,42,16,16
6,6,18,23,8,2012,8,2,28,10,11
7,7,15,8,10,2013,4,0,18,5,8
8,8,21,15,7,2014,3,0,27,12,17
9,9,29,18,9,2015,2,0,67,15,17

In [288]:
q3.describe()

,index,Oost,Zuid,Noord,year,Centrum,Westpoort,NieuwWest,Zuidoost,West
count,10.00000,10.000000,10.00000,10.0000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,4.50000,22.200000,17.30000,13.1000,2010.50000,10.400000,0.600000,37.600000,12.800000,18.600000
std,3.02765,4.263541,6.88073,6.0452,3.02765,6.484169,0.843274,17.180092,4.871687,9.418658
min,0.00000,15.000000,8.00000,7.0000,2006.00000,2.000000,0.000000,18.000000,5.000000,8.000000
25%,2.25000,18.750000,12.75000,9.2500,2008.25000,5.000000,0.000000,27.250000,9.250000,12.250000
50%,4.50000,23.000000,18.00000,11.5000,2010.50000,10.500000,0.000000,31.000000,13.000000,17.000000
75%,6.75000,24.750000,21.25000,14.0000,2012.75000,14.000000,1.000000,42.000000,15.750000,21.750000
max,9.00000,29.000000,30.00000,27.0000,2015.00000,20.000000,2.000000,67.000000,20.000000,39.000000